I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/annaRoute.rpy", line 70, in script
    show annabelle sad
Exception: Image 'annabelle' does not accept attributes 'sad'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/annaRoute.rpy", line 70, in script
    show annabelle sad
  File "renpy/ast.py", line 1192, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1162, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 744, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'annabelle' does not accept attributes 'sad'.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
GameJam 1.0
Sat Aug 14 19:15:04 2021
