I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script
    $ affection -= 1
  File "game/script.rpy", line 49, in <module>
    $ affection -= 1
NameError: name 'affection' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 49, in script
    $ affection -= 1
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 49, in <module>
    $ affection -= 1
NameError: name 'affection' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Test 1.0
Fri Aug 13 17:06:54 2021
